#include "parser_ctx.h"
#include "tac.h"
#include "io_runtime.h"

extern FILE *yyin;
extern FILE *yyout;
extern int line_num;
int yyparse(void);

/* ========= Verbose flag (0=clean output, 1=trace) ========= */
int verbose = 0;

/* ========= The single global parser context ========= */
ParserContext g_ctx = {
    .suppress_exec    = 0,
    .suppress_icg     = 0,
    .current_decl_type = -1,
    .cm_top_idx       = -1,
    .icg_label_top    = -1
};

void yyerror(char *s)
{
    fprintf(stderr, "\nSyntax Error: %s at line %d", s, line_num);
}

int main(void)
{
    /* Open input file */
    yyin = fopen("test.txt", "r");
    if (!yyin) {
        fprintf(stderr, "Error: Cannot open test.txt\n");
        return 1;
    }

    /* Open input.txt for read() statements */
    input_file = fopen("input.txt", "r");
    if (!input_file) {
        fprintf(stderr, "Note: input.txt not found; read() will use stdin\n");
    }

    /* Redirect stdout to testout.txt for execution output */
    yyout = freopen("testout.txt", "w", stdout);

    /* Open ICG output file */
    icg_file = fopen("intermediate_code.txt", "w");
    if (icg_file) {
        fprintf(icg_file, "========================================\n");
        fprintf(icg_file, "   THREE-ADDRESS INTERMEDIATE CODE\n");
        fprintf(icg_file, "   Generated by CSE-3212 Compiler\n");
        fprintf(icg_file, "========================================\n\n");
    }

    /* Parse */
    yyparse();

    /* Close ICG file */
    if (icg_file) {
        fprintf(icg_file, "\n========================================\n");
        fprintf(icg_file, "   Total temporaries used: %d\n", temp_count);
        fprintf(icg_file, "   Total labels used: %d\n", label_count);
        fprintf(icg_file, "========================================\n");
        fclose(icg_file);
    }

    /* Run optimization pass and write optimized code */
    opt_file = fopen("optimized_code.txt", "w");
    if (opt_file) {
        optimize_constant_folding();
        fclose(opt_file);
    }

    /* Close input file if it was opened */
    if (input_file) fclose(input_file);

    /* Write summary to stderr (which is still console) */
    fprintf(stderr, "\n\n=== Compilation Summary ===\n");
    fprintf(stderr, "Execution output: testout.txt\n");
    fprintf(stderr, "Intermediate code: intermediate_code.txt\n");
    fprintf(stderr, "Optimized code: optimized_code.txt\n");
    fprintf(stderr, "===========================\n");

    return 0;
}
